version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  # Mount the init directory
    networks:
      - booking

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8081:8080
    depends_on:
      - postgres
    networks:
      - booking

  redis:
    container_name: redis
    image: redis:alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - booking
    volumes:
      - redis-data:/data

  redis_commander:
    container_name: redis_commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8082:8081
    depends_on:
      - redis
    networks:
      - booking

volumes:
  db-data:
    driver: local
  redis-data:

networks:
  booking:
    driver: bridge